### ISSUE TITLE
Missing Busybox message

### ISSUE THREAD

**Issue by steveboy25** [SpazeDog/mounts2sd#19]
After installation the Mounts2sd say I haven't got busybox on my phone, then my only option is the "close" button. Reinstall, reboot didn't help.

Phone: Xperia X8 (E15i)
Kernel: 2.6.29.6-nAa-14
Rom: MiniCM7-2.2.2-shakira
Busybox: BusyBox v1.20.1-cm7 static (2012-05-28 03:57 +0200) multi-call binary

**Comment by steveboy25** [comment]
It looks to be working well so far after the today update.
I close the issue.
Keep up the good work!

**Comment by dbergloev** [comment]
So my attempt at fixing this actually worked? That is great.
