### ISSUE TITLE
userinit.d script

### ISSUE THREAD

**Issue by sicommnend** [SpazeDog/mounts2sd#2]
I was wondering if you can make a backup script that will be placed in userinit.d just in case of a ROM upgrade. The script in userinit.d can check if the one in init.d has been ran, if it has then it would just exit, if it hasn't been ran then the one in userinit.d will be used.

**Comment by dbergloev** [comment]
I have no idea what you mean, please elaborate. Why would init.d not be
executed? And from where would userinit.d be executed?

**Comment by sicommnend** [comment]
Say you flash a new ROM or update an existing one, usually the system partition is cleaned out which will include /system/etc/init.d. If the ROM flash doesn't require a data wipe then the /data/local/userinit.d folder will still be there for script execution.

Basically a fail safe.

**Comment by dbergloev** [comment]
Yes, and that folder will require something executing it?

**Comment by sicommnend** [comment]
Most ROMs will execute that folder, there may be a few ROMs that do not do this.

**Comment by sicommnend** [comment]
Look for /system/etc/init.d/90userinit, I bet you might have that file on your device.

This is the common name for the file that usually executes that folder. However the name and location may vary from ROM to ROM, it is really up to the ROM developer on how they want to do this or include it. But if I had to estimate, I would estimate about 90% of ROM's use this method.

**Comment by dbergloev** [comment]
I build my ROM's myself, so no. And what you are talking about, does not
execute a folder called userinit.d but a file called userinit. But that
would still work. All you have to do is make the original script add a file
in / indicating it has been executed. Then copy the script to data and add
a check in the top that exists if the file exist

**Comment by sicommnend** [comment]
Here is a sample of the file, mines on my device doesn't have the sd-ext part. https://github.com/elelinux/android_device_htc_hero_ics/blob/master/prebuilt/20userinit
