### ISSUE TITLE
/data/property/m2sd files are empty

### ISSUE THREAD

**Issue by skippernl** [SpazeDog/mounts2sd#9]
Installed 6.0.4
Ran installer and rebooted phone.
The files are there but are empty.
Readahead in gui shows unknown (before with a2sd shows 128 kb)
Manually changing the files works. (used adb pull and push) (m2sd.move_apps/Dalvik/lib)

**Comment by dbergloev** [comment]
You don't have a ROM with this built-in reverse mount script (Can't remember it's name). If the mount point of data and sd-ext is reversed at some point duing boot, it could explain the conflict. Check the m2sd log for an indication that it was unmounting sd-ext which had already been mounted?

**Comment by dbergloev** [comment]
And last, could grab a log while changing an option? And even better if you could direct that log to RootFW

``` bash
logcat | grep -i rootfw
```

**Note**
You need to change tab or close the app (Or just pause it by going to home screen) after doing the change while grabbing the log. M2SD does not write to the file until you lieve the configure tab.

**EDIT**
Never mind, it seams that I am able to reproduce this issue on my own device

``` plain
I/RootFW.ShellExtender::run()( 2700): Running attempt number 1 [echo "" > '/data/property/m2sd.run_sdext_fschk' 2> /dev/null]
```

It echo's nothing ("") to the file. It worked fine yesterday, so I just have to go back and check what the h**\* I changed since then.

**Comment by skippernl** [comment]
The ROM is nikez job.

Could not find any errors in the log even with debug on.

Could it be that a2sd is not properly removed?

Xander
Op 30 aug. 2013 18:26 schreef "Daniel Bergløv" notifications@github.com
het volgende:

**Comment by skippernl** [comment]
Will try this later tonight.

Xander
Op 30 aug. 2013 18:32 schreef "Daniel Bergløv" notifications@github.com
het volgende:

**Comment by skippernl** [comment]
This is the log
V/Setting up the script enviroment
D/Using the shell environment '/data/local/busybox sh'
D/Using the busybox binary located at /data/local/busybox
V/Collecting MMC partition information
V/The external MMC was located at /dev/block/mmcblk0
V/Located the sd-ext partition at /dev/block/mmcblk0p2
V/The internal MMC was located at /dev/block/mtdblock0
V/Located the system partition at /dev/block/mtdblock3
V/Located the data partition at /dev/block/mtdblock5
V/Located the cache partition at /dev/block/mtdblock4
V/Optimizing MMC devices and partitions
V/Setting readahead on /dev/block/mtdblock0 to kb
W/Could not change scheduler on /dev/block/mtdblock0. The scheduler type  is not supported!
V/Setting readahead on /dev/block/mmcblk0 to kb
W/Could not change scheduler on /dev/block/mmcblk0. The scheduler type  is not supported!
V/Setting optimized mount parameters on /dev/block/mtdblock3
V/Setting optimized mount parameters on /dev/block/mtdblock5
V/Setting optimized mount parameters on /dev/block/mtdblock4
D/File system check is disabled. Skipping test on /dev/block/mmcblk0p2
D/The file system type on /dev/block/mmcblk0p2 is not ext4. Disabling journal handling on this device
V/Attaching /dev/block/mmcblk0p2 to /sd-ext
W/The file system type --options is not supported by the kernel. Will try to attach /dev/block/mmcblk0p2 using auto detection!
D/Mounting /dev/block/mmcblk0p2 to /sd-ext as auto with options 'noatime,nodiratime,relatime,nosuid,nodev'
V/Checking writable state on /dev/block/mmcblk0p2
V/Preparing to move content between /data and /sd-ext
V/Checking /data/app to see if something should be moved to /sd-ext/app
V/Attaching /sd-ext/app to /data/app
V/Checking /data/app-private to see if something should be moved to /sd-ext/app-private
V/Attaching /sd-ext/app-private to /data/app-private
V/Checking /data/app-system to see if something should be moved to /sd-ext/app-system
V/Attaching /sd-ext/app-system to /data/app-system
V/Checking /data/data to see if something should be moved to /sd-ext/data
V/Attaching /sd-ext/data to /data/data
V/Checking /data/dalvik-cache to see if something should be moved to /sd-ext/dalvik-cache
V/Attaching /sd-ext/dalvik-cache to /data/dalvik-cache
V/Checking /data/app-asec to see if something should be moved to /sd-ext/app-asec
V/Attaching /sd-ext/app-asec to /data/app-asec
V/Checking /data/app-lib to see if something should be moved to /sd-ext/app-lib
V/Attaching /sd-ext/app-lib to /data/app-lib
D/Running an S-On protection test on /system
V/Linking system content to the /system location
D/Linking content from /data/app-system to /system/app
D/The finalizing sub-process has been started
D/The storage threshold option is disabled, skipping
D/The finalizing sub-process has been stopped
D/The script was executed in 5 seconds

Will wait for a new version to check for issues (getting an error that not all application data has been moved)

**Comment by dbergloev** [comment]
I am working on this, like you say, the problem is the application writing empty content to the files. I think I messed up something in RootFW while fixing some of the null pointer crashes reported in last release. I have not changed anything related to the properties in the app, but the app does use RootFW's File Extender to write them, which I have made some changes to. 

At the moment, I have fixed the script to reset any empty properties to their default values. This will at least stop the script from ever using empty values.

**Comment by dbergloev** [comment]
Okay I found the issue with the properties. RootFW's write() in FileExtender was set to just echo nothing. Have no idea why. I properly changed something and forgot to add the content. But it's fixed. 

Could you please check to see if you have the /data/user directory? I'm trying to understand your warning in the data option. Also could you provide a `busybox df -h` output?
